"""funnel_generator.py — async background task for funnel HTML generation.

FB1: mock-only. Real Claude integration added in FB3.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone

from app.core.database import SessionLocal
from app.services import funnel_service


def _build_mock_html(wizard_input: dict) -> str:
    company = wizard_input.get("company_name", "Company")
    headline = wizard_input.get("hero_headline", "Welcome")
    cta = wizard_input.get("primary_cta_text", "Get Started")
    return f"""<!DOCTYPE html>
<!-- TODO FB3: replace with real Claude generation -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{company}</title>
  <style>
    body {{ font-family: sans-serif; margin: 0; padding: 0; }}
    .hero {{ background: #1a1a2e; color: #fff; padding: 80px 40px; text-align: center; }}
    footer {{ background: #f5f5f5; padding: 20px; text-align: center; color: #888; font-size: 12px; }}
  </style>
</head>
<body>
  <h1 style="text-align:center;padding:20px">{company}</h1>
  <section class="hero">
    <h2>{headline}</h2>
    <button style="margin-top:20px;padding:12px 28px;background:#e94560;color:#fff;border:none;border-radius:4px;font-size:16px;cursor:pointer">{cta}</button>
  </section>
  <footer>Generated by KimuX Funnel Builder (mock &#8212; FB1)</footer>
</body>
</html>"""


async def generate_funnel_async(funnel_id: str, tenant_id: str) -> None:
    """Background task: mock generation with 2-second simulated latency.

    Opens its own DB session — must not receive the request session,
    which is closed before background tasks run in production.
    """
    db = SessionLocal()
    try:
        funnel = funnel_service.mark_generating(db, tenant_id, funnel_id)
        if funnel is None:
            return

        await asyncio.sleep(2)

        wizard_input = funnel.wizard_input or {}
        html = _build_mock_html(wizard_input)
        metadata = {
            "model_used": "mock-fb1",
            "tokens_used": 0,
            "generation_seconds": 2.0,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }
        funnel_service.mark_ready(db, tenant_id, funnel_id, html, metadata)

    except Exception as exc:
        try:
            funnel_service.mark_failed(db, tenant_id, funnel_id, str(exc))
        except Exception:
            pass
    finally:
        db.close()
