"""add_strategy_table

Revision ID: 76e4a04d344d
Revises: 9bc13981c8eb
Create Date: 2026-04-10 21:24:36.700788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e4a04d344d'
down_revision: Union[str, Sequence[str], None] = '9bc13981c8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'generating', 'active', 'archived', name='strategystatus'), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('pricing_model', sa.String(length=50), nullable=True),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('pain_point', sa.Text(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('geography', sa.String(length=50), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('monthly_budget', sa.Float(), nullable=True),
    sa.Column('team_size', sa.String(length=20), nullable=True),
    sa.Column('tried_channels', sa.JSON(), nullable=True),
    sa.Column('primary_goal', sa.String(length=50), nullable=True),
    sa.Column('target_timeline', sa.Integer(), nullable=True),
    sa.Column('strategy_output', sa.JSON(), nullable=True),
    sa.Column('strategy_score', sa.Integer(), nullable=True),
    sa.Column('current_phase', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_user_id'))

    op.drop_table('strategies')
    # ### end Alembic commands ###
