"""add_campaign_activity_communication_offer_integration_tables

Revision ID: 9bc13981c8eb
Revises: 9ea6e43cfcf2
Create Date: 2026-04-02 01:16:26.463049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc13981c8eb'
down_revision: Union[str, Sequence[str], None] = '9ea6e43cfcf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='campaignstatus'), nullable=False),
    sa.Column('objective', sa.String(length=255), nullable=True),
    sa.Column('budget_daily', sa.Float(), nullable=True),
    sa.Column('budget_total', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('offer_name', sa.String(length=255), nullable=True),
    sa.Column('offer_network', sa.String(length=100), nullable=True),
    sa.Column('targeting', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('platform_type', sa.Enum('ad_platform', 'affiliate_network', 'payment_gateway', 'tool', name='platformtype'), nullable=False),
    sa.Column('status', sa.Enum('connected', 'pending', 'disconnected', name='integrationstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index('ix_integrations_platform_name', ['platform_name'], unique=False)
        batch_op.create_index('ix_integrations_tenant_id', ['tenant_id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('aov', sa.Float(), nullable=False),
    sa.Column('gravity', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.Enum('up', 'down', 'stable', name='trenddirection'), nullable=False),
    sa.Column('trend_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='offerstatus'), nullable=False),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index('ix_offers_network', ['network'], unique=False)
        batch_op.create_index('ix_offers_niche', ['niche'], unique=False)
        batch_op.create_index('ix_offers_status', ['status'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('email_sent', 'email_opened', 'email_clicked', 'call', 'meeting', 'form_submit', 'page_visit', 'ad_click', 'chatbot', 'note_added', 'stage_changed', 'score_updated', name='activitytype'), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('performed_by', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index('ix_activities_lead_id_timestamp', ['lead_id', 'timestamp'], unique=False)

    op.create_table('communications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'whatsapp', 'chatbot', 'social_dm', name='communicationchannel'), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='communicationdirection'), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('preview', sa.String(length=100), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communications_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index('ix_communications_lead_id_timestamp', ['lead_id', 'timestamp'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_leads_campaign_id', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leads_campaign_id', type_='foreignkey')

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_index('ix_communications_lead_id_timestamp')
        batch_op.drop_index(batch_op.f('ix_communications_lead_id'))

    op.drop_table('communications')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_lead_id_timestamp')
        batch_op.drop_index(batch_op.f('ix_activities_lead_id'))

    op.drop_table('activities')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index('ix_offers_status')
        batch_op.drop_index('ix_offers_niche')
        batch_op.drop_index('ix_offers_network')

    op.drop_table('offers')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index('ix_integrations_tenant_id')
        batch_op.drop_index('ix_integrations_platform_name')

    op.drop_table('integrations')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
