"""add_lead_table

Revision ID: 9ea6e43cfcf2
Revises: 
Create Date: 2026-04-01 22:04:10.450160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea6e43cfcf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('primary_interest', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_submissions_email'), ['email'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('facebook_ads', 'google_ads', 'tiktok_ads', 'instagram', 'landing_page', 'affiliate_link', 'website_widget', 'api', name='leadsource'), nullable=False),
    sa.Column('source_detail', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.Enum('new', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost', name='leadstage'), nullable=False),
    sa.Column('classification', sa.Enum('hot', 'warm', 'cold', name='leadclassification'), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('ltv', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('affiliate_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_classification', ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index('ix_leads_source', ['source'], unique=False)
        batch_op.create_index('ix_leads_stage', ['stage'], unique=False)
        batch_op.create_index('ix_leads_tenant_id', ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_tenant_id')
        batch_op.drop_index('ix_leads_stage')
        batch_op.drop_index('ix_leads_source')
        batch_op.drop_index(batch_op.f('ix_leads_email'))
        batch_op.drop_index('ix_leads_classification')

    op.drop_table('leads')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_submissions_email'))

    op.drop_table('contact_submissions')
    # ### end Alembic commands ###
